name: pep8_plugin
version: 0.0.1
language: python
description: A python anlayzer for pep8 standard...
tags:
 - python
 - pep8
 - format
 - analyzer
 - plugin

public: true

# clone_in_docker: false

outputs:
  - name: FLOW_PEP8_WARN_COUNT
  - name: FLOW_PEP8_CHECKED_FILE_COUNT
  - name: FLOW_PEP8_LOG_PATH

script_path: ./run.sh
